local Tostring_Result;
local fenv = getfenv();
fenv._aHynncPcS_aU = "This file was protected with MoonSec V3";
pcall(function(a, b, c)
    wait();
end);
fenv.MoonSec_StringsHiddenAttr = true;
task.wait(2);
if pcall(function(a_2, b_2, c_2, ...)
    fenv.setreadonly(
        getrawmetatable(game),
        false
    );
    getrawmetatable(game).__newindex = newcclosure(function(a_3, b_3, c_3, ...)
        if a_3:IsA("TextLabel") then 
            if (b_3 ~= "Text") then
            else 
                Tostring_Result = tostring(c_3);
            end;
        end;
        if Tostring_Result then 

        end;
        local _ = (type(Tostring_Result) ~= "string");
        if not ({
            ["Wood"] = "木头",
            ["Invisible"] = "隐身",
            ["Code"] = "等宽代码",
            ["Distance Check"] = "距离检测",
            ["Mesh"] = "网格",
            ["Utility"] = "工具",
            ["Head"] = "头部",
            ["Mode - Velocity"] = "模式 - 速度",
            ["TriggerBot"] = "触发射击",
            ["Swim"] = "游泳",
            ["Rotation X"] = "旋转X",
            ["Custom"] = "自定义",
            ["Tracers"] = "射线",
            ["DenkOne"] = "登克体",
            ["SafeWalk"] = "安全行走",
            ["Group Id"] = "群组ID",
            ["AutoFire"] = "自动开火",
            ["Gotham"] = "哥谭",
            ["Carpet"] = "地毯",
            ["Water"] = "水",
            ["Ignore invisible"] = "忽略隐身",
            ["Swing range"] = "挥击范围",
            ["CorrodedMetal"] = "腐蚀金属",
            ["Glacier"] = "冰川",
            ["Require right click"] = "需要右键",
            ["Air"] = "空气",
            ["Spin X"] = "X轴旋转",
            ["Physics"] = "物理",
            ["Waypoint"] = "路径点",
            ["Use team color"] = "使用队伍颜色",
            ["SmoothPlastic"] = "光滑塑料",
            ["AutoRejoin"] = "自动重进",
            ["PlayerModel"] = "玩家模型",
            ["Mode - Mouse"] = "模式 - 鼠标",
            ["GothamMedium"] = "哥谭中黑",
            ["Combat"] = "战斗",
            ["Method - Part"] = "方式 - 部件",
            ["Collide"] = "碰撞",
            ["Target particles"] = "目标粒子",
            ["Max targets"] = "最大目标数",
            ["Health Bar"] = "血条",
            ["Impulse"] = "冲量",
            ["Resize"] = "调整大小",
            ["Space/Q"] = "空格/Q",
            ["StaffDetector"] = "管理员检测",
            ["Creepster"] = "怪客体",
            ["Range Circle"] = "显示范围圈",
            ["Salt"] = "盐",
            ["Custom Jump"] = "自定义跳跃",
            ["CrackedLava"] = "熔岩裂缝",
            ["Direct"] = "直接",
            ["Render"] = "渲染",
            ["Neon"] = "霓虹",
            ["RunningNoPhysics"] = "奔跑（无物理）",
            ["Wallbang"] = "穿墙射击",
            ["Outline Transparency"] = "描边透明度",
            ["SourceSansItalic"] = "源泉斜体",
            ["Character"] = "角色",
            ["Movement - CFrame"] = "移动 - 坐标",
            ["SciFi"] = "科幻",
            ["AutoClicker"] = "自动点击",
            ["Show target info"] = "显示目标信息",
            ["Walls"] = "墙体",
            ["Leather"] = "皮革",
            ["Font - Arial"] = "字体 - Arial",
            ["Cartoon"] = "卡通",
            ["Cardboard"] = "纸板",
            ["SpecialElite"] = "特工体",
            ["Priority Only"] = "仅优先目标",
            ["Velocity"] = "速度",
            ["Sandstone"] = "砂岩",
            ["DiamondPlate"] = "菱形钢板",
            ["Chance"] = "几率",
            ["WalkSpeed"] = "行走速度",
            ["World"] = "世界",
            ["Classic"] = "经典",
            ["Highway"] = "高速公路",
            ["Show Background"] = "显示背景",
            ["Blink"] = "闪现",
            ["RobotoCondensed"] = "机器人压缩体",
            ["Climbing"] = "攀爬",
            ["Color"] = "颜色",
            ["Attack range"] = "攻击范围",
            ["BuilderSans"] = "建造者无衬线",
            ["Drawing"] = "绘制",
            ["RotVelocity"] = "旋转速度",
            ["Xray"] = "透视",
            ["Seated"] = "坐下",
            ["Headshot Chance"] = "爆头几率",
            ["Blur background"] = "模糊背景",
            ["KillAura"] = "杀戮光环",
            ["Concrete"] = "混凝土",
            ["Fabric"] = "织物",
            ["Type name"] = "输入名称",
            ["ChatSpammer"] = "聊天刷屏",
            ["LuckiestGuy"] = "幸运哥",
            ["E/Q"] = "E/Q",
            ["Foil"] = "锡箔",
            ["Mode - Random"] = "模式 - 随机",
            ["Cobblestone"] = "圆石",
            ["Bodoni"] = "博多尼",
            ["Hit Chance"] = "命中几率",
            ["MouseTP"] = "鼠标传送",
            ["Jura"] = "尤拉",
            ["WoodPlanks"] = "木板",
            ["SilentAim"] = "静默瞄准",
            ["Plastic"] = "塑料",
            ["Motor"] = "马达",
            ["Arrows"] = "箭头",
            ["Rainbow speed"] = "彩虹速度",
            ["Reach"] = "攻击范围",
            ["Roblox username"] = "Roblox 用户名",
            ["Mode - Workspace"] = "模式 - 工作区",
            ["Modules"] = "模块",
            ["Retro"] = "复古",
            ["Mode - Click"] = "模式 - 点击",
            ["Merriweather"] = "梅里韦瑟",
            ["Michroma"] = "米克罗玛",
            ["Rejoin Previous Server"] = "重进上一个服务器",
            ["Mode - Uninject"] = "模式 - 卸载",
            ["Player"] = "玩家",
            ["PlatformStand"] = "固定站立",
            ["Projectile"] = "弹道",
            ["Arimo"] = "阿里莫",
            ["Metal"] = "金属",
            ["Rubber"] = "橡胶",
            ["GUI Theme - new"] = "界面主题 - 新",
            ["Ignored Scripts"] = "忽略脚本",
            ["Material - ForceField"] = "材质 - 力场",
            ["Range"] = "范围",
            ["Climb State"] = "攀爬状态",
            ["ESP"] = "透视",
            ["GothamBlack"] = "哥谭特黑",
            ["FallingDown"] = "跌落",
            ["AmaticSC"] = "阿玛提克",
            ["MurderMystery"] = "谋杀之谜",
            ["RoofShingles"] = "屋瓦",
            ["Friends"] = "好友",
            ["FFlag"] = "标志",
            ["default"] = "默认",
            ["Blatant"] = "显性",
            ["AntiFall"] = "防摔",
            ["Glass"] = "玻璃",
            ["HighJump"] = "高跳",
            ["Priority - Action4"] = "优先级 - 动作4",
            ["Users"] = "用户",
            ["Role Rank"] = "角色等级",
            ["Target"] = "目标",
            ["PatrickHand"] = "帕特里克手写",
            ["Render players through walls"] = "渲染穿墙玩家",
            ["Parts"] = "部件",
            ["Float Mode - Velocity"] = "浮空模式 - 速度",
            ["Garamond"] = "伽罗蒙",
            ["To send"] = "发送数据",
            ["Rejoin"] = "重进",
            ["Speed Mode - Velocity"] = "速度模式 - 速度",
            ["Timer"] = "时间倍率",
            ["Move Mode - MoveDirection"] = "移动模式 - 移动方向",
            ["Method - FindPartOnRay"] = "方式 - 射线检测",
            ["Mode - Impulse"] = "模式 - 冲量",
            ["Ignore behind walls"] = "忽略墙后",
            ["Panic"] = "紧急关闭",
            ["Outline Color"] = "描边颜色",
            ["HitBoxes"] = "碰撞箱",
            ["Nunito"] = "努尼托",
            ["PermanentMarker"] = "粗头笔",
            ["Keys - Space/LeftControl"] = "按键 - 空格/左Ctrl",
            ["SpinBot"] = "自旋机器人",
            ["Granite"] = "花岗岩",
            ["Mode - 部件"] = "模式 - 部件",
            ["Reinject"] = "重新注入",
            ["Lerp"] = "插值",
            ["LeafyGrass"] = "草丛",
            ["Parkour"] = "跑酷",
            ["General"] = "常规",
            ["ButtonA/ButtonL2"] = "手柄A/手柄L2",
            ["Instant"] = "瞬间",
            ["Expand amount"] = "扩展量",
            ["Legacy"] = "传统",
            ["Jump Power"] = "跳跃力度",
            ["Anti-AFK"] = "防挂机",
            ["Space/LeftShift"] = "空格/左Shift",
            ["GettingUp"] = "起身",
            ["SourceSansLight"] = "源泉细体",
            ["Pebble"] = "鹅卵石",
            ["Pavement"] = "人行道",
            ["Ice"] = "冰",
            ["Notifications"] = "通知",
            ["GUI"] = "界面",
            ["Self destruct"] = "自毁",
            ["Reset current profile"] = "重置当前配置",
            ["Mode - Highlight"] = "模式 - 高亮",
            ["IndieFlower"] = "手写花体",
            ["Targets"] = "目标",
            ["Toggle alert"] = "切换提醒",
            ["Sort GUI"] = "整理界面",
            ["Reset GUI positions"] = "重置界面位置",
            ["Filled"] = "填充",
            ["Rainbow update rate"] = "彩虹刷新率",
            ["JosefinSans"] = "约瑟芬无衬线",
            ["Gradient"] = "渐变",
            ["BuilderSansMedium"] = "建造者中黑",
            ["GUI bind indicator"] = "界面绑定提示",
            ["Rainbow Mode - Normal"] = "彩虹模式 - 普通",
            ["FOV"] = "视野范围",
            ["Auto rescale"] = "自动缩放",
            ["Show legit mode"] = "显示合法模式",
            ["AutoJump"] = "自动跳跃",
            ["Face target"] = "面向目标",
            ["Show tooltips"] = "显示提示",
            ["Profiles"] = "配置",
            ["Sarpanch"] = "萨潘奇",
            ["TitilliumWeb"] = "提提利安",
            ["Search"] = "搜索",
            ["Rebind GUI"] = "重新绑定界面",
            ["GUI Theme"] = "界面主题",
            ["Unknown"] = "未知",
            ["Delay"] = "延迟",
            ["Antique"] = "古典",
            ["Gravity"] = "重力",
            ["Freecam"] = "自由视角",
            ["ServerHop"] = "跳服",
            ["StrafingNoPhysics"] = "横移（无物理）",
            ["Ascending"] = "升序",
            ["Arcade"] = "街机",
            ["RobotoMono"] = "机器人等宽体",
            ["old"] = "旧",
            ["Bounding Box"] = "边框",
            ["Rotation Z"] = "旋转Z",
            ["NameTags"] = "头顶名牌",
            ["Lines"] = "行数",
            ["Type - Movement Only"] = "类型 - 仅移动",
            ["Pulse"] = "脉冲",
            ["Marble"] = "大理石",
            ["Hide Flood Message"] = "隐藏刷屏提示",
            ["Animation"] = "动作",
            ["AnimationPlayer"] = "动作播放器",
            ["Spin Z"] = "Z轴旋转",
            ["Humanoid State - None"] = "人形状态 - 无",
            ["Spin Y"] = "Y轴旋转",
            ["Kalam"] = "卡拉姆",
            ["RightClick"] = "右键",
            ["Show target"] = "显示目标",
            ["BodyMover"] = "物理移动",
            ["Rock"] = "岩石",
            ["Name"] = "名字",
            ["Local"] = "本地",
            ["Roboto"] = "机器人",
            ["Oswald"] = "奥斯瓦尔德",
            ["Part - RootPart"] = "部位 - 身体",
            ["Landed"] = "着陆",
            ["Fantasy"] = "奇幻",
            ["Ragdoll"] = "布娃娃",
            ["Basalt"] = "玄武岩",
            ["Ignore none"] = "不忽略",
            ["Group"] = "群组",
            ["CeramicTiles"] = "瓷砖",
            ["Teams by server"] = "按服务器分组",
            ["TP"] = "传送",
            ["Use Displayname"] = "使用显示名",
            ["GrenzeGotisch"] = "哥特边界",
            ["Settings"] = "Kenny汉化b站UID:1531514159",
            ["Jumping"] = "跳跃",
            ["Mode - 2D"] = "模式 - 2D",
            ["Fondamento"] = "方达门托",
            ["Slate"] = "板岩",
            ["Tool"] = "工具",
            ["Texture"] = "纹理",
            ["Sword lunge only"] = "仅剑冲刺",
            ["Require mouse down"] = "需要按住鼠标",
            ["Max angle"] = "最大角度",
            ["Ubuntu"] = "优班图",
            ["Health"] = "生命值",
            ["AimAssist"] = "辅助瞄准",
            ["Attacks per Second"] = "每秒攻击次数",
            ["Auto Disable"] = "自动关闭",
            ["Transparency"] = "透明度",
            ["Freefall"] = "自由落体",
            ["Inventory"] = "物品栏",
            ["Sort - Descending"] = "排序 - 降序",
            ["Player Color"] = "玩家颜色",
            ["Custom Properties"] = "自定义属性",
            ["AntiRagdoll"] = "防布娃娃",
            ["Grass"] = "草地",
            ["Vertical Speed"] = "垂直速度",
            ["Move Mode - Impulse"] = "移动模式 - 冲量",
            ["TargetStrafe"] = "环绕走位",
            ["Minigames"] = "小游戏",
            ["Phase"] = "穿墙",
            ["LongJump"] = "远跳",
            ["Scale"] = "缩放",
            ["Bangers"] = "爆破体",
            ["Running"] = "奔跑",
            ["Brick"] = "砖块",
            ["Fly"] = "飞行",
            ["Plaster"] = "灰泥",
            ["Mode - CFrame"] = "模式 - 坐标",
            ["FredokaOne"] = "弗雷多卡",
            ["Chams"] = "透视上色",
            ["Mode - TouchInterest"] = "模式 - 碰撞判定",
            ["CPS"] = "每秒点击次数",
            ["Spider"] = "蜘蛛爬行",
            ["Ground"] = "土地",
            ["Speed"] = "加速",
            ["Disabler"] = "禁用器",
            ["Rotation Y"] = "旋转Y",
            ["Enable Multi-Keybinding"] = "启用多重按键绑定",
            ["ClayRoofTiles"] = "陶瓦",
            ["SourceSans"] = "源泉黑体",
            ["Asphalt"] = "沥青",
            ["GamingChair"] = "高亮座椅",
            ["Mud"] = "泥巴",
            ["Snow"] = "雪",
            ["Sand"] = "沙子",
            ["Limestone"] = "石灰岩"
        })[Tostring_Result] then
        else 
            getrawmetatable(game).__newindex(a_3, b_3);
            game[b_3] = nil;
        end;
    end);
    fenv.setreadonly(
        getrawmetatable(game),
        true
    );
end) then 

end;
if pcall(function(a_3, b_3, c_3, ...)
    loadstring(
        game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true)
    )();
end) then 
end;
